'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lótus_1._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1301418555_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1301418555_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306471349_MAIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1306471349_MAIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306549341_monotone_close_exit_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1306549341_monotone_close_exit_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307073561_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1307073561_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307073578_media_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1307073578_media_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307073583_media_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1307073583_media_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1308621475_Printer_and_Fax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1308621475_Printer_and_Fax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property balao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property balde_tinta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balde_tinta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CCleaner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCleaner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property consultar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property display_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property display_tema() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display_tema", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo_padrao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo_padrao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Graphing_Spreadsheets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Graphing_Spreadsheets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hard_Drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hard_Drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis1_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis1_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis2_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis2_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis3_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis3_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis4_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis4_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis5_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis5_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis6_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis6_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lapis7_icone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lapis7_icone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Livro() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Livro", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Recycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remover_todos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remover_todos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restaurar_banco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restaurar_banco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rigth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rigth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sede() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sede", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Word_Processor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Word_Processor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Writing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Writing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
